export const SIGN_IN_FACEBOOK_REQUEST = '@auth/SIGN_IN_FACEBOOK_REQUEST';
export const SIGN_IN_FACEBOOK_SUCCESS = '@auth/SIGN_IN_FACEBOOK_SUCCESS';
export const SIGN_IN_FACEBOOK_FAILURE = '@auth/SIGN_IN_FACEBOOK_FAILURE';

export const SIGN_IN_GOOGLE_REQUEST = '@auth/SIGN_IN_GOOGLE_REQUEST';
export const SIGN_IN_GOOGLE_SUCCESS = '@auth/SIGN_IN_GOOGLE_SUCCESS';
export const SIGN_IN_GOOGLE_FAILURE = '@auth/SIGN_IN_GOOGLE_FAILURE';
