export const SIGN_IN_FACEBOOK_REQUEST = 'SIGN_IN_FACEBOOK_REQUEST ';
export const SIGN_IN_FACEBOOK_SUCCESS = 'SIGN_IN_FACEBOOK_SUCCESS ';
export const SIGN_IN_FACEBOOK_FAILURE = 'SIGN_IN_FACEBOOK_FAILURE ';
